// Code generated by godin. DO NOT EDIT.

package ticket

import (
	"context"
)

// Service is the main interface which is derived from the protobuf API specification ('TicketService')
type Service interface {
	Create(ctx context.Context, title string, description string) (ticket *Ticket, err error)
	Get(ctx context.Context, id string) (ticket *Ticket, err error)
}
