// Code generated by godin. DO NOT EDIT.
package endpoint

import (
	"context"
	"github.com/go-kit/kit/endpoint"

	. "github.com/go-godin/godin/examples/ticket/internal/ticket"
)

type Set struct {
	CreateEndpoint endpoint.Endpoint
	GetEndpoint    endpoint.Endpoint
}

func NewEndpointSet(svc Service) Set {

	var create endpoint.Endpoint
	{
		create = MakeCreateEndpoint(svc)
	}
	var get endpoint.Endpoint
	{
		get = MakeGetEndpoint(svc)
	}

	return Set{
		CreateEndpoint: create,
		GetEndpoint:    get,
	}
}

func (s Set) Create(ctx context.Context, title string, description string) (ticket Ticket, err error) {
	resp, err := s.CreateEndpoint(ctx, CreateRequest{Title: title, Description: description})
}

func (s Set) Get(ctx context.Context, id string) (ticket Ticket, err error) {
	resp, err := s.GetEndpoint(ctx, GetRequest{Id: id})
}
