// Code generated by godin. DO NOT EDIT.
package endpoint

import (
	. "github.com/go-godin/godin/examples/ticket/internal/ticket"
)

// CreateRequest wraps the request fields of the Create Endpoint.
type CreateRequest struct {
	Title       string
	Description string
}

// CreateResponse wraps the response fields of the Create Endpoint, adding an error field
// implementing the Failer interface.
type CreateResponse struct {
	Ticket *Ticket
	Err    error
}

// GetRequest wraps the request fields of the Get Endpoint.
type GetRequest struct {
	Id string
}

// GetResponse wraps the response fields of the Get Endpoint, adding an error field
// implementing the Failer interface.
type GetResponse struct {
	Ticket *Ticket
	Err    error
}

func (r CreateResponse) Failed() error { return r.Err }
func (r GetResponse) Failed() error    { return r.Err }
